### ISSUE TITLE
Some URLs aren't found despite existing on reddit

### ISSUE THREAD

**Issue by ghost** [aabbi/GetComments#2]
At the moment the link to https://www.reddit.com/r/todayilearned/comments/dgtege/til_france_has_a_law_allowing_colleagues_to_gift/ doesn't work. Clicking around, some work and some don't.

[Example video](https://streamable.com/jaana)

**Comment by aabbi** [comment]
@LoveIsGrief released a new version which hopefully fixes the issue. Pls let me know if it works for you or if there are other urls on which it still isnt working.

**Comment by ghost** [comment]
Hi. Thanks for the quick fix! It's working on more URLs now than before :+1:
